title: Dayda
name: Dayda
user_description: Making data more discoverable and usable.
resources_url: "https://simply-jekyll.netlify.app"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: Dayda
baseurl: "/"
url: "http://127.0.0.1:4000/"
encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-feed 
  - jekyll-sitemap 

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
    resources:
      output: true
      permalink: /resources/:title

disqus:
  shortname: raghuveerdotnet

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
  - scope:
      path: ""
      type: resources
    values:
      layout: post
      content-type: resources
