title: Dayda
name: Template
user_description: Making data more discoverable and usable.
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
url: http://127.0.0.1:4000/
encoding: utf-8
paginate: 10
paginate_path: /page:num/
markdown: kramdown